//
//  Human.swift
//  Uvex
//
//  Created by Emil Shirima on 8/29/16.
//  Copyright © 2016 Alphamicron Inc. All rights reserved.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

import UIKit

class Human: NSObject
{
    class func drawSlice1(frame frame: CGRect = CGRect(x: 0, y: 0, width: 140, height: 335), resizing: ResizingBehavior = .AspectFill)
    {
        let context = UIGraphicsGetCurrentContext()!
        
        /// Background Color
        UIColor.whiteColor().setFill()
        CGContextFillRect(context, CGContextGetClipBoundingBox(context))
        
        /// Resize To Frame
        CGContextSaveGState(context)
        let resizedFrame = resizing.apply(rect: CGRect(x: 0, y: 0, width: 140, height: 335), target: frame)
        CGContextTranslateCTM(context, resizedFrame.minX, resizedFrame.minY)
        let resizedScale = CGSize(width: resizedFrame.width / 140, height: resizedFrame.height / 335)
        CGContextScaleCTM(context, resizedScale.width, resizedScale.height)
        CGContextTranslateCTM(context, -319, -60)
        
        /// Fill 277
        let fill277 = UIBezierPath()
        fill277.moveToPoint(CGPoint(x: 334, y: 84.36))
        fill277.addLineToPoint(CGPoint(x: 334, y: 73.42))
        fill277.addCurveToPoint(CGPoint(x: 318.55, y: 75.93), controlPoint1: CGPoint(x: 330.44, y: 71), controlPoint2: CGPoint(x: 323.27, y: 75.27))
        fill277.addCurveToPoint(CGPoint(x: 301.8, y: 79.13), controlPoint1: CGPoint(x: 312.84, y: 76.73), controlPoint2: CGPoint(x: 307.32, y: 78.07))
        fill277.addCurveToPoint(CGPoint(x: 263.24, y: 79.44), controlPoint1: CGPoint(x: 289.86, y: 81.41), controlPoint2: CGPoint(x: 276.4, y: 77.03))
        fill277.addCurveToPoint(CGPoint(x: 245.38, y: 78.39), controlPoint1: CGPoint(x: 256.24, y: 80.72), controlPoint2: CGPoint(x: 251.71, y: 79.58))
        fill277.addCurveToPoint(CGPoint(x: 191.73, y: 71.81), controlPoint1: CGPoint(x: 231.6, y: 75.78), controlPoint2: CGPoint(x: 205.26, y: 72.49))
        fill277.addLineToPoint(CGPoint(x: 191.66, y: 68.22))
        fill277.addCurveToPoint(CGPoint(x: 244.98, y: 61.73), controlPoint1: CGPoint(x: 203.23, y: 67.5), controlPoint2: CGPoint(x: 233.16, y: 64.14))
        fill277.addCurveToPoint(CGPoint(x: 281.92, y: 60.9), controlPoint1: CGPoint(x: 264.01, y: 57.84), controlPoint2: CGPoint(x: 261.63, y: 62.66))
        fill277.addCurveToPoint(CGPoint(x: 317.64, y: 63.97), controlPoint1: CGPoint(x: 306.47, y: 58.76), controlPoint2: CGPoint(x: 297.93, y: 61.2))
        fill277.addCurveToPoint(CGPoint(x: 334, y: 66.83), controlPoint1: CGPoint(x: 323.18, y: 64.74), controlPoint2: CGPoint(x: 329.89, y: 68.59))
        fill277.addLineToPoint(CGPoint(x: 334, y: 55.43))
        fill277.addLineToPoint(CGPoint(x: 333.55, y: 54.11))
        fill277.addCurveToPoint(CGPoint(x: 331.52, y: 47.55), controlPoint1: CGPoint(x: 333.03, y: 52.01), controlPoint2: CGPoint(x: 332.8, y: 49.98))
        fill277.addCurveToPoint(CGPoint(x: 304.91, y: 50.43), controlPoint1: CGPoint(x: 324.15, y: 46.14), controlPoint2: CGPoint(x: 320.07, y: 54.05))
        fill277.addCurveToPoint(CGPoint(x: 279.73, y: 42.87), controlPoint1: CGPoint(x: 296.31, y: 48.37), controlPoint2: CGPoint(x: 288.33, y: 44.95))
        fill277.addCurveToPoint(CGPoint(x: 252.34, y: 43.37), controlPoint1: CGPoint(x: 266.94, y: 39.8), controlPoint2: CGPoint(x: 264.47, y: 40.1))
        fill277.addCurveToPoint(CGPoint(x: 223.01, y: 41.21), controlPoint1: CGPoint(x: 248.11, y: 44.51), controlPoint2: CGPoint(x: 227.51, y: 42.3))
        fill277.addCurveToPoint(CGPoint(x: 194.96, y: 36.98), controlPoint1: CGPoint(x: 214.02, y: 39.04), controlPoint2: CGPoint(x: 204.27, y: 38.18))
        fill277.addCurveToPoint(CGPoint(x: 165.37, y: 36.09), controlPoint1: CGPoint(x: 183.95, y: 35.55), controlPoint2: CGPoint(x: 176.81, y: 34.01))
        fill277.addCurveToPoint(CGPoint(x: 123.03, y: 42.27), controlPoint1: CGPoint(x: 145.23, y: 39.75), controlPoint2: CGPoint(x: 152.61, y: 43.78))
        fill277.addCurveToPoint(CGPoint(x: 115.8, y: 41.66), controlPoint1: CGPoint(x: 120.77, y: 42.16), controlPoint2: CGPoint(x: 117.96, y: 41.83))
        fill277.addCurveToPoint(CGPoint(x: 111.72, y: 41.45), controlPoint1: CGPoint(x: 114.43, y: 41.55), controlPoint2: CGPoint(x: 113.06, y: 41.56))
        fill277.addCurveToPoint(CGPoint(x: 108.42, y: 40.25), controlPoint1: CGPoint(x: 109.73, y: 41.28), controlPoint2: CGPoint(x: 109.25, y: 41.11))
        fill277.addCurveToPoint(CGPoint(x: 149.25, y: 29.46), controlPoint1: CGPoint(x: 117.89, y: 34.53), controlPoint2: CGPoint(x: 122.74, y: 42.43))
        fill277.addCurveToPoint(CGPoint(x: 167.51, y: 22.03), controlPoint1: CGPoint(x: 153.99, y: 27.14), controlPoint2: CGPoint(x: 161.25, y: 21.91))
        fill277.addCurveToPoint(CGPoint(x: 192.35, y: 21.14), controlPoint1: CGPoint(x: 172.35, y: 22.13), controlPoint2: CGPoint(x: 188.8, y: 22.19))
        fill277.addCurveToPoint(CGPoint(x: 187.58, y: 18.53), controlPoint1: CGPoint(x: 191.34, y: 18.96), controlPoint2: CGPoint(x: 189.73, y: 19.07))
        fill277.addCurveToPoint(CGPoint(x: 188.06, y: 18.24), controlPoint1: CGPoint(x: 187.72, y: 18.41), controlPoint2: CGPoint(x: 187.76, y: 18.28))
        fill277.addCurveToPoint(CGPoint(x: 192.59, y: 17.38), controlPoint1: CGPoint(x: 189.14, y: 18.07), controlPoint2: CGPoint(x: 186.8, y: 17.93))
        fill277.addCurveToPoint(CGPoint(x: 196.38, y: 15.57), controlPoint1: CGPoint(x: 194.28, y: 17.21), controlPoint2: CGPoint(x: 195.62, y: 17.14))
        fill277.addCurveToPoint(CGPoint(x: 184.29, y: 13.42), controlPoint1: CGPoint(x: 194.24, y: 12.89), controlPoint2: CGPoint(x: 187.7, y: 14.78))
        fill277.addCurveToPoint(CGPoint(x: 196.73, y: 9.67), controlPoint1: CGPoint(x: 187.02, y: 11.53), controlPoint2: CGPoint(x: 195.17, y: 13.48))
        fill277.addCurveToPoint(CGPoint(x: 191.72, y: 8.69), controlPoint1: CGPoint(x: 195.4, y: 8.48), controlPoint2: CGPoint(x: 194.71, y: 8.63))
        fill277.addCurveToPoint(CGPoint(x: 185.63, y: 8.76), controlPoint1: CGPoint(x: 189.66, y: 8.73), controlPoint2: CGPoint(x: 187.7, y: 8.83))
        fill277.addLineToPoint(CGPoint(x: 187.47, y: 7.57))
        fill277.addCurveToPoint(CGPoint(x: 189.65, y: 6.56), controlPoint1: CGPoint(x: 188.11, y: 7.24), controlPoint2: CGPoint(x: 188.95, y: 6.91))
        fill277.addCurveToPoint(CGPoint(x: 192.37, y: 3.05), controlPoint1: CGPoint(x: 191.48, y: 5.65), controlPoint2: CGPoint(x: 192.11, y: 5.51))
        fill277.addCurveToPoint(CGPoint(x: 176.24, y: 6.43), controlPoint1: CGPoint(x: 186.52, y: 2.58), controlPoint2: CGPoint(x: 181.24, y: 6.72))
        fill277.addCurveToPoint(CGPoint(x: 181.49, y: 0.06), controlPoint1: CGPoint(x: 178.58, y: 4.4), controlPoint2: CGPoint(x: 181.76, y: 3.9))
        fill277.addCurveToPoint(CGPoint(x: 160.65, y: 11.38), controlPoint1: CGPoint(x: 174.87, y: -0.83), controlPoint2: CGPoint(x: 164.8, y: 8.9))
        fill277.addCurveToPoint(CGPoint(x: 132.87, y: 16.37), controlPoint1: CGPoint(x: 153.6, y: 15.58), controlPoint2: CGPoint(x: 142.73, y: 14.37))
        fill277.addCurveToPoint(CGPoint(x: 107.96, y: 24.1), controlPoint1: CGPoint(x: 124.05, y: 18.16), controlPoint2: CGPoint(x: 122.69, y: 21.93))
        fill277.addCurveToPoint(CGPoint(x: 76.23, y: 25.18), controlPoint1: CGPoint(x: 98, y: 25.56), controlPoint2: CGPoint(x: 86.58, y: 24.94))
        fill277.addCurveToPoint(CGPoint(x: 43.53, y: 57.8), controlPoint1: CGPoint(x: 45.04, y: 25.92), controlPoint2: CGPoint(x: 62.89, y: 56.72))
        fill277.addCurveToPoint(CGPoint(x: 26.01, y: 51.23), controlPoint1: CGPoint(x: 34.68, y: 58.29), controlPoint2: CGPoint(x: 28.3, y: 51.88))
        fill277.addCurveToPoint(CGPoint(x: 19.92, y: 53.18), controlPoint1: CGPoint(x: 20.83, y: 49.78), controlPoint2: CGPoint(x: 24.76, y: 53.01))
        fill277.addCurveToPoint(CGPoint(x: 2.94, y: 60.37), controlPoint1: CGPoint(x: 12.81, y: 53.44), controlPoint2: CGPoint(x: 7.2, y: 53.49))
        fill277.addCurveToPoint(CGPoint(x: 1.48, y: 63.15), controlPoint1: CGPoint(x: 2.5, y: 61.09), controlPoint2: CGPoint(x: 1.88, y: 62.24))
        fill277.addCurveToPoint(CGPoint(x: 0.86, y: 64.67), controlPoint1: CGPoint(x: 1.23, y: 63.73), controlPoint2: CGPoint(x: 1.09, y: 64.17))
        fill277.addLineToPoint(CGPoint(x: 0.24, y: 65.84))
        fill277.addCurveToPoint(CGPoint(x: 0, y: 66.23), controlPoint1: CGPoint(x: 0.18, y: 65.94), controlPoint2: CGPoint(x: 0.09, y: 66.11))
        fill277.addLineToPoint(CGPoint(x: 0, y: 73.45))
        fill277.addCurveToPoint(CGPoint(x: 19.39, y: 86.87), controlPoint1: CGPoint(x: 3.22, y: 78.59), controlPoint2: CGPoint(x: 2.95, y: 86.96))
        fill277.addCurveToPoint(CGPoint(x: 25.12, y: 89), controlPoint1: CGPoint(x: 25.05, y: 86.84), controlPoint2: CGPoint(x: 20.6, y: 89.44))
        fill277.addCurveToPoint(CGPoint(x: 30.21, y: 86), controlPoint1: CGPoint(x: 27.62, y: 88.76), controlPoint2: CGPoint(x: 28.61, y: 86.88))
        fill277.addCurveToPoint(CGPoint(x: 35.83, y: 83.56), controlPoint1: CGPoint(x: 32.32, y: 84.84), controlPoint2: CGPoint(x: 33.41, y: 85.13))
        fill277.addCurveToPoint(CGPoint(x: 42.98, y: 82.22), controlPoint1: CGPoint(x: 38.01, y: 82.16), controlPoint2: CGPoint(x: 39.67, y: 82.11))
        fill277.addCurveToPoint(CGPoint(x: 56.1, y: 101.83), controlPoint1: CGPoint(x: 54.12, y: 82.57), controlPoint2: CGPoint(x: 54.08, y: 92.58))
        fill277.addCurveToPoint(CGPoint(x: 120.41, y: 118.99), controlPoint1: CGPoint(x: 60.8, y: 123.39), controlPoint2: CGPoint(x: 96.14, y: 109.42))
        fill277.addCurveToPoint(CGPoint(x: 132.53, y: 123.58), controlPoint1: CGPoint(x: 125.1, y: 120.84), controlPoint2: CGPoint(x: 126.76, y: 122.37))
        fill277.addCurveToPoint(CGPoint(x: 160.33, y: 128.46), controlPoint1: CGPoint(x: 140.84, y: 125.33), controlPoint2: CGPoint(x: 153.54, y: 124.32))
        fill277.addCurveToPoint(CGPoint(x: 181.22, y: 139.82), controlPoint1: CGPoint(x: 163.96, y: 130.68), controlPoint2: CGPoint(x: 176.27, y: 141.5))
        fill277.addLineToPoint(CGPoint(x: 181.38, y: 138.94))
        fill277.addCurveToPoint(CGPoint(x: 176.52, y: 133.51), controlPoint1: CGPoint(x: 181.2, y: 135.95), controlPoint2: CGPoint(x: 178.11, y: 135.45))
        fill277.addCurveToPoint(CGPoint(x: 192.34, y: 136.97), controlPoint1: CGPoint(x: 181.9, y: 133.86), controlPoint2: CGPoint(x: 186.87, y: 137.46))
        fill277.addCurveToPoint(CGPoint(x: 185.67, y: 131.33), controlPoint1: CGPoint(x: 191.95, y: 132.84), controlPoint2: CGPoint(x: 188.59, y: 133.86))
        fill277.addCurveToPoint(CGPoint(x: 196.42, y: 130.94), controlPoint1: CGPoint(x: 188.82, y: 131.17), controlPoint2: CGPoint(x: 193.63, y: 131.9))
        fill277.addCurveToPoint(CGPoint(x: 190.92, y: 127.87), controlPoint1: CGPoint(x: 196.64, y: 128.58), controlPoint2: CGPoint(x: 196.13, y: 128.57))
        fill277.addCurveToPoint(CGPoint(x: 183.89, y: 126.64), controlPoint1: CGPoint(x: 188.83, y: 127.59), controlPoint2: CGPoint(x: 185.49, y: 127.67))
        fill277.addCurveToPoint(CGPoint(x: 196.37, y: 124.9), controlPoint1: CGPoint(x: 187.55, y: 125.09), controlPoint2: CGPoint(x: 193.02, y: 126.67))
        fill277.addCurveToPoint(CGPoint(x: 186.35, y: 122.29), controlPoint1: CGPoint(x: 195.48, y: 121.8), controlPoint2: CGPoint(x: 189.77, y: 122.59))
        fill277.addCurveToPoint(CGPoint(x: 192.38, y: 118.88), controlPoint1: CGPoint(x: 188.63, y: 120.89), controlPoint2: CGPoint(x: 191.07, y: 121.36))
        fill277.addCurveToPoint(CGPoint(x: 168.07, y: 117.97), controlPoint1: CGPoint(x: 189.17, y: 117.85), controlPoint2: CGPoint(x: 172.7, y: 117.77))
        fill277.addCurveToPoint(CGPoint(x: 130.18, y: 103.41), controlPoint1: CGPoint(x: 158.47, y: 118.36), controlPoint2: CGPoint(x: 147.97, y: 107.08))
        fill277.addCurveToPoint(CGPoint(x: 107.48, y: 99.16), controlPoint1: CGPoint(x: 120.92, y: 101.5), controlPoint2: CGPoint(x: 115.42, y: 103.75))
        fill277.addCurveToPoint(CGPoint(x: 138.02, y: 97.49), controlPoint1: CGPoint(x: 110.94, y: 97.81), controlPoint2: CGPoint(x: 132.72, y: 97.4))
        fill277.addCurveToPoint(CGPoint(x: 164.32, y: 103.66), controlPoint1: CGPoint(x: 147.07, y: 97.66), controlPoint2: CGPoint(x: 154.9, y: 101.78))
        fill277.addCurveToPoint(CGPoint(x: 193.85, y: 103.18), controlPoint1: CGPoint(x: 176.16, y: 106.02), controlPoint2: CGPoint(x: 182.62, y: 104.39))
        fill277.addCurveToPoint(CGPoint(x: 222.43, y: 98.93), controlPoint1: CGPoint(x: 203.21, y: 102.17), controlPoint2: CGPoint(x: 213.64, y: 100.94))
        fill277.addCurveToPoint(CGPoint(x: 251.52, y: 96.43), controlPoint1: CGPoint(x: 227.38, y: 97.8), controlPoint2: CGPoint(x: 247.13, y: 95.46))
        fill277.addCurveToPoint(CGPoint(x: 279.32, y: 97.25), controlPoint1: CGPoint(x: 263.52, y: 99.09), controlPoint2: CGPoint(x: 263.27, y: 101.15))
        fill277.addCurveToPoint(CGPoint(x: 318.33, y: 89.2), controlPoint1: CGPoint(x: 292.27, y: 94.11), controlPoint2: CGPoint(x: 306.68, y: 86.79))
        fill277.addCurveToPoint(CGPoint(x: 331.79, y: 92.33), controlPoint1: CGPoint(x: 322.75, y: 90.12), controlPoint2: CGPoint(x: 325.8, y: 93.31))
        fill277.addCurveToPoint(CGPoint(x: 334, y: 84.36), controlPoint1: CGPoint(x: 332.18, y: 91.11), controlPoint2: CGPoint(x: 333.87, y: 84.54))
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 389, 228)
        CGContextRotateCTM(context, 450 * CGFloat(M_PI/180))
        CGContextTranslateCTM(context, -167, -70)
        fill277.usesEvenOddFillRule = true
        UIColor(hue: 0.55, saturation: 1, brightness: 0.768, alpha: 1).setFill()
        fill277.fill()
        CGContextRestoreGState(context)
        
        CGContextRestoreGState(context)
    }
    
    class func imageOfSlice1(size size: CGSize = CGSize(width: 140, height: 335), resizing: ResizingBehavior = .AspectFit) -> UIImage
    {
        var image: UIImage
        
        UIGraphicsBeginImageContextWithOptions(size, false, 0)
        Human.drawSlice1(frame: CGRect(origin: CGPoint.zero, size: size), resizing: resizing)
        image = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        
        return image
    }
    
    enum ResizingBehavior
    {
        case AspectFit /// The content is proportionally resized to fit into the target rectangle.
        case AspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case Stretch /// The content is stretched to match the entire target rectangle.
        case Center /// The content is centered in the target rectangle, but it is NOT resized.
        
        func apply(rect rect: CGRect, target: CGRect) -> CGRect
        {
            if rect == target || target == CGRect.zero
            {
                return rect
            }
            
            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)
            
            switch self
            {
            case .AspectFit:
                scales.width = min(scales.width, scales.height)
                scales.height = scales.width
            case .AspectFill:
                scales.width = max(scales.width, scales.height)
                scales.height = scales.width
            case .Stretch:
                break
            case .Center:
                scales.width = 1
                scales.height = 1
            }
            
            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }    
}